package tests;

public class Question_Answer {
    /*
    How many locators are there?
    --8 locators.

    What are they?
    --id, name, className, linkText, tagName, partialLinkText, xpath, css

    Which one do you prefer? Why?
    --Ahmet's answer:
        -First if there is an Id, use id, cause id is unique and fast
        -If there is no Id then i use name if there is a unique name
        -But i also create dynamic xpath, because some elements do not have stable attributes like id and name
        -And i can write xpath for any element
        -I sometimes even use css selector instead of xpath, but i personally use xpath more than css.

    What is difference between absolute xpath and relative xpath?
        Absolute xpath we start from the parent and go child elements one by one.
        Absolute xpath may easily be broken when a new element is added an the page
        for this reason we should never use absolute xpath.
        In fact my team dont let QA's use absolute xpath.

        Relative xpath we dont start from parent and go child one by one. We go straight to the element
        Relative xpath is very reliable it does not easy brake, because Relative xpath does not dependent on other element
        I use Relative xpath in my framework when to locate the elements

    What is difference between absolute xpath and css selector?
        First xpath and css are similar. Both are helpful and there are different ways to xpath or css
        Syntax is little different
        in xpath we ı use // and @, but in css we do not
        css is a little faster than xpath(way less than 1 second).
        xpath does navigation in the html that takes a little bit time(way less than 1 second).
        there are more ways to write xpath. for exp: dynamic xpath has contains starts with, end withs functions

    What is a dropdown?
       Dropdown is a webelement. It has list of options.

    How do you handle dropdown? What do you do to automate dropdown?
        Dropdowns are created using Select class. So we first locate the dropdown element, then use select class
        to interact with dropdown elements.

    How We actually have 3 options to select a dropdown(index,value,visible text)

    What is an alert?
         Alerts are a pop up that is generated by javascript.
         When there is an alerts, we must handle the alerts.
         Otherwise, we cannot continue to the test execution

    How do you handle alert?
        First we cannot inspect js alerts. We should first switch
        to the alert and use accept() to click ok, dismiss() to
        click cancel, sendKeys() to type, getText() to get the
        text from the alert

    What might be the reason for your test case to fail?
        There may be wait problem. The page may be very slow or internet maybe not fast.
            Put some more wait. We can use explicit wait in selenium.
        Locator might be incorrect.
            Double check locator and fix if needed.
        Data issue. Type in our expected values.
            If there is any documentation issue, we can talk to BA to fix the document
            and then we can use correct expected values.
        Maybe there is an iframe on the page.
            We first need to switch to the frame
        Maybe there is an alert on the page.
            We first need to handle the alert by accepting or dismissing
        It may be a real bug that is caused by the latest codes.
            We discuss the issue with the team then raise a bug ticket if needed



            Actions-Actions Class nedir?
                Actions selenium dan gelen bir kütüphanedir.
                Mouse ve Keyboard işlemlerini gerçekleştirmek için kullandığımız hazır bir selenium kütüphanesidir.
                Örneğin; sağ tıklamak(contextClick), çift tıklamak(doubleClick), elementin üzerine gitmek(moveToElement) gibi.
                Ayrıca shift, control, delete, enter gibi tuşlara da actions yardımıyla basabiliriz, bu tür işlemlerde sendKeys metodu kullanılır.

             Ne tür methodlar kullandın?
                Actions metotları önemlidir
                ve tekrar kullanmam gerektiğinden, actions methodları içeren reusable metodlar oluşturdum
                ve gerektiğinde onları çağirarak kullanıyorum.
                Örneğin, contextClick metodunu bir elemente sağ tıklamak için test classımdan direk çağırabilirim.





        Tell me 5 exception that you get/What type of exceptions do you get in selenium?
            Null pointer, no such element, time out, slate element reference, web driver

        What is your solution?
            Read the error message and learn what is the error and where it is.
            In general, error happens because of the timing issue, wrong locator, or iframe/windows/alerts
            Each error has specific solutions but in general, I debug my code,
            and do some research then execute the code one more time after the fix.

        What type of waits do you use?
            I use implicit or explicit wait

        Which wait do you prefer?
            Explicit wait works better in some cases. When I use explicit wait,
            and still see timeout exception, then there can be other issues such as incorrect locators.

        Why do you prefer that wait?
            I already have implicit wait in my Driver class,
            but I prefer explicit wait when I need to use an expected condition such as element is not visible.

        How do you resolve synronization issue?
            I use implicit or explicit wait. In my driver class, I already have implicit wait,
            that handles most of the wait issues, but when it is not enough than I use explicit wait.


       Test dataları kimden gelir?
            1.BA-Business Analyst--BA acceptance criteria ları yazar
            2.Test Lead
            3.Manuel Tester
            4.Tech Lead & Team Lead & Dev Lead
            5.Developer
            6.DataBase
            7.API call lar
            8.Documentasyonlar örn: Swagger
            9.Java Faker-- fake datalar için

            ---Scrum Master veya end-user dan data gelmez


     */
}
